spring.application.name=backend

server.port=8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs

razorpay.api.key=${RAZORPAY_API_KEY}
razorpay.api.secret=${RAZORPAY_API_SECRET}